[package]
name = "cadmus_objects"
version = "0.1.0"
edition = "2021"

[dependencies]
cadmus_util = { version = "0.1.0", path = "../cadmus_util" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
