-- Add migration script here
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  username varchar(128) NOT NULL UNIQUE,

  pwd varchar(256) NOT NULL,
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  name varchar(256) NOT NULL
);
